
let test =
{
    array: h => h.array || h.err('must be an array'),
    arrayOrString: fn => h => h.or(h.string, h.array) ? h.to(fn) : h.err('must be an array or a string'),
    boolean: h => h.bool || h.err('must be set to true or false'),
    function: h => h.func || h.err('must be a function'),
    functionOrNull: h => h.or(h.null, h.func) || h.err('must be a function or null'),
    functionOrString: h => h.or(h.string, h.func) || h.err('must be a function or a string'),
    functionOrStringOrNull: h => h.or(h.null, h.string, h.func) || h.err('must be a function or a string or null'),
    object: h => h.plain || h.err('must be an object'),
    objectOrArray: fn => h => h.or(h.array, h.plain) ? h.to(fn) : h.err('must be an object or an array'),
    objectOrString: fn => h => h.or(h.string, h.plain) ? h.to(fn) : h.err('must be an object or a string'),
    positiveOrNull: h => h.or(h.null, h.and(h.number, h.gte(1))) || h.err('must be a positive integer or null'),
    regex: h => h.of(RegExp) || h.err('must be a regular expression'),
    regexOrString: h => h.or(h.of(RegExp), h.string) || h.err('must be a regular expression or a string'),
    string: h => h.string || h.err('must be a string'),
    stringOrBoolean: h => h.or(h.string, h.bool) || h.err('must be a string or a boolean'),
    unset: h => h.undef || h.err('is not a valid property'),
    zeroPlus: h => h.and(h.number, h.gte(0)) || h.err('must be zero or more')
};

export default
{
    'config': { test: test.object, default: {}, merge: true },
    'config.*': test.unset,
    'config.convert': { test: test.object, default: {}, merge: true },
    'config.convert.*': test.unset,
    'config.convert.autolink': test.functionOrStringOrNull,
    'config.convert.code': test.functionOrStringOrNull,
    'config.convert.codeblock': test.functionOrStringOrNull,
    'config.convert.divide': test.functionOrStringOrNull,
    'config.convert.email': test.functionOrStringOrNull,
    'config.convert.emphasis': test.functionOrStringOrNull,
    'config.convert.fenceblock': test.functionOrStringOrNull,
    'config.convert.header': test.functionOrStringOrNull,
    'config.convert.html': test.functionOrStringOrNull,
    'config.convert.htmlblock': test.functionOrStringOrNull,
    'config.convert.image': test.functionOrStringOrNull,
    'config.convert.linebreak': test.functionOrStringOrNull,
    'config.convert.link': test.functionOrStringOrNull,
    'config.convert.listitem': test.functionOrStringOrNull,
    'config.convert.olist': test.functionOrStringOrNull,
    'config.convert.paragraph': test.functionOrStringOrNull,
    'config.convert.quotation': test.functionOrStringOrNull,
    'config.convert.root': test.functionOrStringOrNull,
    'config.convert.setext': test.functionOrStringOrNull,
    'config.convert.strong': test.functionOrStringOrNull,
    'config.convert.ulist': test.functionOrStringOrNull,
    'config.convertTabsAfter': { test: test.array, default: [] },
    'config.convertTabsAfter.*': test.string,    
    'config.delousers': { test: test.object, default: {}, merge: true },
    'config.delousers.*': test.objectOrArray(),
    'config.delousers.*.*': test.unset,
    'config.delousers.*.replace': test.functionOrString,
    'config.delousers.*.search': test.arrayOrString(f => f.string([ f.value ])),
    'config.delousers.*.search.*': test.unset,
    'config.delousers.*.search.0': test.string,
    'config.delousers.*.search.1': test.string,
    'config.delousers.*<array>': test.array,
    'config.delousers.*<array>.*': test.string,
    'config.entities': { test: test.object, default: {}, merge: true },
    'config.entities.*': test.object,
    'config.entities.*.*': test.unset,
    'config.entities.*.delouse': { test: test.object, default: {} },
    'config.entities.*.delouse.*': test.array,
    'config.entities.*.delouse.*.*': test.functionOrString,
    'config.entities.*.name': test.string,
    'config.entities.*.nestable': { test: test.array, default: [] },
    'config.entities.*.nestable.*': test.string,
    'config.entities.*.order': { test: test.zeroPlus, default: 1000000 },
    'config.entities.*.pattern': test.string,
    'config.entities.*.patternData': { test: test.object, default: {} },
    'config.entities.*.priority': { test: test.zeroPlus, default: 1000000 },
    'config.fm': { test: test.object, default: {}, merge: true },
    'config.fm.*': test.unset,
    'config.fm.enabled': test.boolean,
    'config.fm.capture': test.regex,
    'config.fm.parser': test.function,
    'config.fm.useConfig': test.stringOrBoolean,
    'config.fm.varsOnly': test.boolean,
    'config.interpolation': { test: test.object, default: {}, merge: true },
    'config.interpolation.*': test.unset,
    'config.interpolation.segments': test.regexOrString,
    'config.interpolation.variables': test.regexOrString,
    'config.onAction': test.functionOrNull,
    'config.onConvert': test.functionOrNull,
    'config.refs': { test: test.object, default: {}, merge: true },
    'config.refs.*': test.objectOrString(f => f.string({ url: f.value })),
    'config.refs.*.*': test.unset,
    'config.refs.*.title': test.string,
    'config.refs.*.url': test.string,
    'config.tabSize': test.positiveOrNull,
    'config.vars': { test: test.object, default: {}, merge: true }
}
